ServiceName = "backend-service"
Name = ""
Description = "An example backend service"
Owners = ["roylibman@gmail.com"]
ServerFramework = "go-server"
ServerMain = ""
ArtifactRepository = "me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo"
Domain = "cluster.koalaops.com"
Port = 8080

[KoalaVersionInfo]
  Version = "1.1.147"
  DeployWorkflowVersion = "1.1.174"

[Repo]
  Name = "backend-service"
  GitUser = "koala-sandbox"
  URL = ""
  Path = ""
  IsMonorepo = false

[OpenAPIConfig]
  SpecPath = "api/openapi.yaml"
  QueryPath = ""
  CodegenTool = "openapi-generator"

[[Environments]]
  Name = "dev"
  Namespace = "dev"
  Cluster = "koala-demo-cluster"
  Location = "me-west1"
  CloudProvider = "gcp"
  IngressEnabled = true
  IngressHost = "dev.backend-service.koala-demo-cluster.cluster.koalaops.com"
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false
    HPAEnabled = false
    HPAMaxReplicas = 0
    HPATargetCPUUtilizationPercentage = 0
    HPATargetMemoryUtilizationPercentage = 0

[[Environments]]
  Name = "prod"
  Namespace = "prod"
  Cluster = "koala-demo-cluster"
  Location = "me-west1"
  CloudProvider = "gcp"
  IngressEnabled = true
  IngressHost = "prod.backend-service.koala-demo-cluster.cluster.koalaops.com"
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false
    HPAEnabled = false
    HPAMinReplicas = 1
    HPAMaxReplicas = 5
    HPATargetCPUUtilizationPercentage = 70
    HPATargetMemoryUtilizationPercentage = 70

[[Environments]]
  Name = "staging"
  Namespace = "staging"
  Cluster = "koala-demo-cluster"
  Location = "me-west1"
  CloudProvider = "gcp"
  IngressEnabled = true
  IngressHost = "staging.backend-service.koala-demo-cluster.cluster.koalaops.com"
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false
    HPAEnabled = false
    HPAMaxReplicas = 0
    HPATargetCPUUtilizationPercentage = 0
    HPATargetMemoryUtilizationPercentage = 0

[[Environments]]
  Name = "autopush"
  Namespace = "autopush"
  Cluster = "koala-demo-cluster"
  Location = "me-west1"
  CloudProvider = "gcp"
  IngressEnabled = true
  IngressHost = "autopush.backend-service.koala-demo-cluster.cluster.koalaops.com"
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false
    HPAEnabled = false
    HPAMaxReplicas = 0
    HPATargetCPUUtilizationPercentage = 0
    HPATargetMemoryUtilizationPercentage = 0

[SSLConfig]
  CertName = "backend-service-tls-cert"
  Issuer = "letsencrypt"
  IssuerContactEmail = "roylibman@gmail.com"

[Metrics]
  Collector = ""
  [Metrics.Endpoint]
    Path = ""
    Port = 0
    Scheme = ""
    Interval = ""

[Tracing]
  Backend = ""
  URL = ""

[Profiling]
  Tool = ""
