apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  replicas: "3"
  selector:
    matchLabels:
      app: backend-service
  template:
    spec:
      containers:
        - name: backend-service
          image: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/backend-service:latest
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 750m
              memory: 500Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-service-configmap
    metadata:
      labels:
        app: backend-service
